esp_toml_version = 1.0

firmware_images_url = "https://embedded.plode.org/bins/"

supported_apps = ["PLAYCOMPUTER","ROBOKI","ZING0", "ZING1","HEXAPOD","4DOF", "OID_PEN", "PLICKER", "KLAW", "TOY_ROBOTIC_ARM", "3D_PRINTER_MB", "3D_PRINTER_DISPALY","TEST", "DS_CALIBRATE"]

[PLAYCOMPUTER]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "playcomputer0.1/playcomputer0.1.bin"
image.esp32-s3 = "playcomputer/playcomputer.bin"

# Optional: This should be a publicly accessible URL of the application configuration markdown file
# The markdown file will display the application configuration.
# It might include details such as the revisions of esp-idf, esp-matter, etc. or any other application configuration
config_readme_url = "<APP_CONFIG_README_FILE_URL>"

[ROBOKI]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "roboki/roboki.bin"


[ZING0]
chipsets = ["ESP32"]
image.esp32 = "zing0.1/zing0.1.bin"


[ZING1]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "zing/zing.bin"
image.esp32-s3 = "zing2.0/zing2.0.bin"


[HEXAPOD]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "crawlee1.0/crawlee1.0.bin"
image.esp32-s3 = "crawlee2.0/crawlee2.0.bin"


[4DOF]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "4dof_zing/4dof_zing.bin"


[OID_PEN]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "oid_pen/oid_pen.bin"


[PLICKER]
chipsets = ["ESP32-C2"]
image.esp32-h2 = "plicker/plicker.bin"


[KLAW]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "klaw/klaw.bin"


[TOY_ROBOTIC_ARM]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "toy-robotic-arm/toy-robotic-arm.bin"


[3D_PRINTER_MB]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter/3dprinter.bin"


[3D_PRINTER_DISPALY]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter_disp/3dprinter_disp.bin"


[TEST]
chipsets = ["ESP32","ESP32-S3","ESP32-H2","ESP32-C2","ESP32-C3"]
image.esp32 = "test-firmware/esp32/test-firmware.bin"
image.esp32-s3 = "test-firmware/esp32s3/test-firmware.bin"
image.esp32-h2 = "test-firmware/esp32h2/test-firmware.bin"
image.esp32-c2 = "test-firmware/esp32c2/test-firmware.bin"
image.esp32-c3 = "test-firmware/esp32c3/test-firmware.bin"


[DS_CALIBRATE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ds_servo_calibrate/ds_servo_calibrate.bin"
