esp_toml_version = 1.0

firmware_images_url = "https://embedded.plode.org/bins/"

supported_apps = ["PLAYCOMPUTER","ROBOKI","ZING-0.1", "ZING","HEXAPOD","4DOF", "OID_PEN", "PLICKER", "ROBOTIC_ARM", "TOY_ROBOTIC_ARM", "3D_PRINTER_MB", "3D_PRINTER_DISPALY","TEST", "DS_CALIBRATE"]

[PLAYCOMPUTER]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "playcomputer0.1/playcomputer0.1.bin"
image.esp32-s3 = "playcomputer/playcomputer.bin"
ios_app_url = ""
android_app_url = ""

[ROBOKI]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "roboki/roboki.bin"
ios_app_url = ""
android_app_url = ""

[ZING-0.1]
chipsets = ["ESP32"]
image.esp32 = "zing0.1/zing0.1.bin"
ios_app_url = ""
android_app_url = ""

[ZING]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "zing/zing.bin"
image.esp32-s3 = "zing2.0/zing2.0.bin"
ios_app_url = ""
android_app_url = ""

[HEXAPOD]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "crawlee_1.0/crawlee_1.0.bin"
image.esp32-s3 = "hexapod/hexapod.bin"
ios_app_url = ""
android_app_url = ""

[4DOF]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "4dof_zing/4dof_zing.bin"
ios_app_url = ""
android_app_url = ""

[OID_PEN]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "oid_pen/oid_pen.bin"
ios_app_url = ""
android_app_url = ""

[PLICKER]
chipsets = ["ESP32-C2"]
image.esp32-h2 = "plicker/plicker.bin"
ios_app_url = ""
android_app_url = ""

[ROBOTIC_ARM]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "robotic-arm/robotic-arm.bin"
ios_app_url = ""
android_app_url = ""

[TOY_ROBOTIC_ARM]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "toy-robotic-arm/toy-robotic-arm.bin"
ios_app_url = ""
android_app_url = ""

[3D_PRINTER_MB]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter/3dprinter.bin"
ios_app_url = ""
android_app_url = ""

[3D_PRINTER_DISPALY]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter_disp/3dprinter_disp.bin"
ios_app_url = ""
android_app_url = ""

[TEST]
chipsets = ["ESP32","ESP32-S3","ESP32-H2","ESP32-C2","ESP32-C3"]
image.esp32 = "test-firmware/esp32/test-firmware.bin"
image.esp32-s3 = "test-firmware/esp32s3/test-firmware.bin"
image.esp32-h2 = "test-firmware/esp32h2/test-firmware.bin"
image.esp32-c2 = "test-firmware/esp32c2/test-firmware.bin"
image.esp32-c3 = "test-firmware/esp32c3/test-firmware.bin"
ios_app_url = ""
android_app_url = ""

[DS_CALIBRATE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ds_servo_calibrate/ds_servo_calibrate.bin"
ios_app_url = ""
android_app_url = ""
